default: &defaults
  docker:
    - image: gcr.io/andela-learning/circlebuildenv:v4
      auth:
        username: _json_key
        password: '${SERVICE_ACCOUNT_JSON_KEY}'

  working_directory: ~/repo

  environment:
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3200m
    TERM: dumb

version: 2
jobs:
  android_lint:
    <<: *defaults
    steps:
      - checkout:
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      
      # Running static analysis tools
      - run:
          name: Running quality checks
          command: |
            echo "Run android lint"
            ./gradlew lint
      
      # Storing reports
      - store_artifacts:
          path: app/build/reports
      
      # Sending notification
      - run:
          name: Notifying slack channel (succeeded)
          when: on_success
          command: |
            bash .circleci/notify_slack.sh
      - run:
          name: Notifying slack channel (failed)
          when: on_fail
          command: |
            bash .circleci/notify_slack_fail.sh

  findbugs_lint:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      
      # Running static analysis tools
      - run:
          name: Running quality checks
          command: |
            echo "Run findbugs"
            ./gradlew assemble
            ./gradlew findbugs
      
      # Storing reports
      - store_artifacts:
          path: app/build/outputs
      
      # Sending notification
      - run:
          name: Notifying slack channel (succeeded)
          when: on_success
          command: |
            bash .circleci/notify_slack.sh
      - run:
          name: Notifying slack channel (failed)
          when: on_fail
          command: |
            bash .circleci/notify_slack_fail.sh

  pmd_lint:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      
      # Running static analysis tools
      - run:
          name: Running quality checks
          command: |
            echo "Run PMD"
            ./gradlew pmd
      
      # Storing reports
      - store_artifacts:
          path: app/build
      
      # Sending notification
      - run:
          name: Notifying slack channel (succeeded)
          when: on_success
          command: |
            bash .circleci/notify_slack.sh
      - run:
          name: Notifying slack channel (failed)
          when: on_fail
          command: |
            bash .circleci/notify_slack_fail.sh

  checkstyle_lint:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      
      # Running static analysis tools
      - run:
          name: Running quality checks
          command: |
            echo "Run checkstyle"
            ./gradlew checkstyle
      
      # Storing reports
      - store_artifacts:
          path: app/build/reports
      
      # Sending notification
      - run:
          name: Notifying slack channel (succeeded)
          when: on_success
          command: |
            bash .circleci/notify_slack.sh
      - run:
          name: Notifying slack channel (failed)
          when: on_fail
          command: |
            bash .circleci/notify_slack_fail.sh

  unit_test:
    <<: *defaults 
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # Running unit tests
      - run:
          name: Running unit tests on source code
          command: |
            mv /home/.secrets ~/repo
            ./gradlew build jacocoTestReport assembleAndroidTest
      
      # Storing unit test reports
      - store_artifacts:
          path: app/build/reports/jacoco
          destination: reports
      - store_artifacts:
          path: app/build/reports/tests
          destination: reports
      
      # Sending notification
      - run:
          name: Notifying slack channel on succeed
          when: on_success
          command: |
            bash <(curl -s https://codecov.io/bash)
            bash .circleci/notify_slack.sh
      - run:
          name: Notifying slack channel on fail
          when: on_fail
          command: |
            bash <(curl -s https://codecov.io/bash)
            bash .circleci/notify_slack_fail.sh

  instrumented_test:
    <<: *defaults 
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      
      # Build apk with instrumented tests
      - run:
          name: Creating an apk file with instrumented tests
          command: |
            mv /home/.secrets ~/repo
            ./gradlew build :app:assembleDebug :app:assembleAndroidTest -PdisablePreDex

      # Set project ID and use the service account
      - run:
          name: Set gcloud project ID and authenticate service account
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud config set project $GCP_PROJECT_ID

      # Send test apk to firebase
      - run:
          name: Run instrumented tests on firebase
          command: |
            gcloud beta firebase test android run \
            --type instrumentation \
            --app app/build/outputs/apk/debug/app-debug.apk \
            --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
            --directories-to-pull=/sdcard/tmp \
            --timeout 20m \
            --results-bucket art-firebase-test-results
      # Get test reports from the storage bucket
      - run:
          name: Download test reports from storage bucket
          when: always
          command: |
            REPORTS_DIR=$(gsutil ls gs://art-firebase-test-results | tail -1)
            mkdir ~/reports
            gsutil cp -r $REPORTS_DIR ~/reports

      # Storing instrumented test reports
      - store_artifacts:
          path: ~/reports
          destination: reports

      # Sending notification
      - run:
          name: Notifying slack channel on succeed
          when: on_success
          command: |
            echo $CIRCLE_ARTIFACTS
            bash .circleci/notify_slack.sh

      - run:
          name: Notifying slack channel on fail
          when: on_fail
          command: |
            echo $CIRCLE_ARTIFACTS
            bash .circleci/notify_slack_fail.sh

    #   - post:
          # Download the test bucket content as CircleCI artifact
        #   - gsutil -m cp -r -U `sudo gsutil ls gs://cloud-test-circle-ctl-test | tail -1` $CIRCLE_ARTIFACTS/ | true

  deploy_test_build:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # Building apk files for debug and release
      - run:
          name: Assembling apk
          command: |
            ./gradlew :app:assemble

      # Storing the generated apk files and reports
      - store_artifacts:
          path: app/build/outputs/apk/prod/debug
      - store_artifacts:
          path: app/build/outputs/apk/prod/release
      - store_artifacts:
          path: app/build/reports
          destination: reports

      # Sending notification
      - run:
          name: Notifying slack channel on succeed
          when: on_success
          command: |
            bash .circleci/notify_slack.sh
      - run:
          name: Notifying slack channel on fail
          when: on_fail
          command: |
            bash .circleci/notify_slack_fail.sh

  deploy_staging_build:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # Building apk files for debug and release
      - run:
          name: Assembling apk
          command: |
            ./gradlew :app:assemble

      # Storing the generated apk files and reports
      - store_artifacts:
          path: app/build/outputs/apk/prod/debug
      - store_artifacts:
          path: app/build/outputs/apk/prod/release
      - store_artifacts:
          path: app/build/reports
          destination: reports

      # Sending notification
      - run:
          name: Notifying slack channel on succeed
          when: on_success
          command: |
            bash .circleci/notify_slack.sh
      - run:
          name: Notifying slack channel on fail
          when: on_fail
          command: |
            bash .circleci/notify_slack_fail.sh

  deploy_production_build:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # Building apk files for debug and release
      - run:
          name: Assembling apk
          command: |
            ./gradlew :app:assembleRelease

      # Storing the generated apk files and reports
      - store_artifacts:
          path: app/build/outputs/apk/prod/debug
      - store_artifacts:
          path: app/build/outputs/apk/prod/release
      - store_artifacts:
          path: app/build/reports
          destination: reports

      # Sending notification
      - run:
          name: Notifying slack channel on succeed
          when: on_success
          command: |
            bash .circleci/notify_slack.sh
      - run:
          name: Notifying slack channel on fail
          when: on_fail
          command: |
            bash .circleci/notify_slack_fail.sh

workflows:
  version: 2
  lint_test_and_deployment:
    jobs:
      - android_lint
      - findbugs_lint
      - pmd_lint
      - checkstyle_lint
      - unit_test:
          requires:
            - android_lint
            - findbugs_lint
            - pmd_lint
            - checkstyle_lint
      - instrumented_test
      - deploy_test_build:
          requires:
            - unit_test
            - instrumented_test
          filters:
            branches:
              only: develop
      - deploy_staging_build:
          requires:
            - unit_test
            - instrumented_test
          filters:
            branches:
              only: staging
      - deploy_production_build:
          requires:
            - unit_test
            - instrumented_test
          filters:
            branches:
              only: master
